- id: doi:10.1109/TRO.2020.3043688
  type: paper
  description:  We proposed a novel approach for simultaneously solving the unknown matrices.
  image: https://raw.githubusercontent.com/perceptioncqu/perception-group/main/images/tro_21.png
  buttons:
    - type: source
      text: Manuscript Source
      link: https://ieeexplore.ieee.org/document/9319563     
  tags:
    - calibration and identification
    - dual arm manipulation
    - multirobot systems

- id: doi:10.1109/TMECH.2021.3131309
  image: https://raw.githubusercontent.com/perceptioncqu/perception-group/main/images/tmech_2022.png

- id: doi:10.1109/TRO.2021.3108506
  type: paper
  description:  We proposed a novel method that plan and optimize a robotic machining path that meets the requirements of smoothness, dexterity, and stiffness based on the point cloud from onsite measurement.
  image: https://raw.githubusercontent.com/perceptioncqu/perception-group/main/images/tro_23.png
  buttons:
    - type: source
      text: Manuscript Source
      link: https://ieeexplore.ieee.org/document/9642395   
  tags:
    - Intelligent and flexible manufacturing
    - motion and path planning
    - optimization and optimal control
    - robot machining system

- id: doi:10.1109/TII.2023.3240747
  image: https://raw.githubusercontent.com/perceptioncqu/perception-group/main/images/tii_2023.png

- id: doi:10.1109/TIM.2024.3370160
  image: https://raw.githubusercontent.com/perceptioncqu/perception-group/main/images/tim_wang.png

- id: doi:10.1109/TIM.2024.3412212
  image: https://raw.githubusercontent.com/perceptioncqu/perception-group/main/images/tim_huang.png

- id: doi:10.1109/JSEN.2023.3306371
  image: https://raw.githubusercontent.com/perceptioncqu/perception-group/main/images/sensor_j_luo.png
  
- id: doi:10.1109/TMECH.2017.2665652
  image: https://raw.githubusercontent.com/perceptioncqu/perception-group/main/images/tmech_2017.png

- id: doi:10.1016/j.cja.2018.09.005
  image: https://raw.githubusercontent.com/perceptioncqu/perception-group/main/images/wang_2017.png

- id: doi:10.1007/s00170-017-0358-2 
  image: https://raw.githubusercontent.com/perceptioncqu/perception-group/main/images/wang_2017_ijam.png

- id: doi:10.1109/ICRA57147.2024.10610312
  image: https://raw.githubusercontent.com/perceptioncqu/perception-group/main/images/ICRA_huang.png

- id: doi:10.1088/0957-0233/27/9/095003
  image: https://raw.githubusercontent.com/perceptioncqu/perception-group/main/images/mst_li.png

- id: doi:10.1109/ICRA57147.2024.10611053
  image: https://raw.githubusercontent.com/perceptioncqu/perception-group/main/images/ICRA_wang.png

  - id: doi:10.1016/j.suscom.2023.100923
  image: https://raw.githubusercontent.com/perceptioncqu/perception-group/main/images/luo_2022.png

  - id: 10.1109/TMECH.2024.3446528
  image: https://raw.githubusercontent.com/perceptioncqu/perception-group/main/images/tmech_2024.png




